### PR TITLE
Add composer.json

### PR DESCRIPTION
**Pull request by hensoko**
This PR adds a composer.json to allow loading dev-master from composer directly (when using typo3-composer repository a custom repository may be necessary).

### CODE REVIEW

**Comment by kaystrobach** [comment]
could you please rebase that PR? - thank you

**Comment by hensoko** [comment]
Done. I removed the version field because composer is fully compatible with using git-tags instead. Additionally I removed the extra-section because it is only necessary for TYPO3 itself and should be contained in root composer.json.

**Comment by kaystrobach** [comment]
@hensoko problem is, that TYPO3 6.2 depends on that "version" entry in composer.json and will otherwise throw weird exceptions

**Comment by kaystrobach** [comment]
we ship a composer.json now

**Pull request closed without merging**
